In [ ]:
import pandas as pd
import seaborn as sns 
from scipy import stats
from sklearn.preprocessing import MinMaxScaler

#Spajanje vise skupova podataka
data=pd.read_csv("Metro_Interstate_Traffic_Volume.csv")


#upis podataka u file
#data.to_csv("C:/Users/Nikola Petrovic/Desktop/ML/Data/PHASE_Data/metro.csv", index=False)

#provera da li ima missing values
#data.isna().sum()

#brisanje duplikata
#data.duplicated(subset=None, keep='first')
#data.drop_duplicates(subset=None, keep='first')

#prikaz podataka klasa
#sns.countplot(x='traffic_volume', data=data)

#sortiranje i opis podataka
#data.describe()
#data.sort_values('Phase')
#data=data['1']/data['1'].max()

#skaliranje podataka
#df2 = pd.unique(data[['holiday', 'rain_1h', 'snow_1h', 'weather_main', 'weather_description']].values.ravel())
#df2 = pd.unique(data[['holiday']].values.ravel())
#df2 = pd.unique(data[['rain_1h']].values.ravel())
df3 = pd.unique(data[['snow_1h']].values.ravel())
df2 = pd.unique(data[['weather_main']].values.ravel())
#df2 = pd.unique(data[['weather_description']].values.ravel())

data['holiday'] = data['holiday'].replace(
    ['None', 'Columbus Day', 'Veterans Day', 'Thanksgiving Day', 'Christmas Day',
    'New Years Day', 'Washingtons Birthday', 'Memorial Day', 'Independence Day',
    'State Fair', 'Labor Day', 'Martin Luther King Jr Day'], 
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

data['weather_main'] = data['weather_main'].replace(
    ['Clouds', 'Clear', 'Rain', 'Drizzle', 'Mist', 'Haze', 'Fog', 'Thunderstorm',
    'Snow', 'Squall', 'Smoke'], 
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data['weather_description'] = data['weather_description'].replace(
    ['scattered clouds', 'broken clouds', 'overcast clouds', 'sky is clear',
    'few clouds', 'light rain', 'light intensity drizzle', 'mist', 'haze', 'fog',
    'proximity shower rain', 'drizzle', 'moderate rain', 'heavy intensity rain',
    'proximity thunderstorm', 'thunderstorm with light rain',
    'proximity thunderstorm with rain', 'heavy snow', 'heavy intensity drizzle',
    'snow', 'thunderstorm with heavy rain', 'freezing rain', 'shower snow',
    'light rain and snow', 'light intensity shower rain', 'SQUALLS',
    'thunderstorm with rain', 'proximity thunderstorm with drizzle',
    'thunderstorm', 'Sky is Clear', 'very heavy rain',
    'thunderstorm with light drizzle', 'light snow',
    'thunderstorm with drizzle', 'smoke', 'shower drizzle', 'light shower snow',
    'sleet'], 
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37 ])

scaler = MinMaxScaler()

data[['clouds_all']] = scaler.fit_transform(data[['clouds_all']])
data[['temp']]=scaler.fit_transform(data[['temp']])

data.rename(columns = {'temp':'Temperature'}, inplace = True)
#df2 = pd.unique(data[['weather_description']].values.ravel())
#print(df2)
#data["holiday"]

# df = pd.DataFrame([
#                    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37 ]], 
#                    columns=['TempScaled'])
# display(df)
# df_max_scaled = df.copy()
            
# for column in df_max_scaled.columns:
#     df_max_scaled[column] = df_max_scaled[column]  / df_max_scaled[column].abs().max()
      
# view normalized data
#display(df_max_scaled)
print("cofi")
#data.head(3000)
data[['clouds_all']]

       clouds_all
0            0.40
1            0.75
2            0.90
3            0.90
4            0.75
...           ...
48199        0.75
48200        0.90
48201        0.90
48202        0.90
48203        0.90

[48204 rows x 1 columns]